In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [9]:
## sentences
sent=[ 'the glass of milk', 
    'the glass of juice',
    'the cup of tea',
    'I am good boy',
    'I a good developer',
    'understand the meaning of words',
    'your videos are good',]

In [10]:
## define the vocabllury size
voc_size = 10000

In [11]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am good boy',
 'I a good developer',
 'understand the meaning of words',
 'your videos are good']

In [12]:
## One hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr



[[8689, 8540, 7571, 9726],
 [8689, 8540, 7571, 3456],
 [8689, 6634, 7571, 4490],
 [4232, 2022, 5760, 5615],
 [4232, 6697, 5760, 6982],
 [5474, 8689, 9121, 7571, 9069],
 [6471, 5422, 99, 5760]]

In [17]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [19]:
sent_len = 8
embedding_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)
print(embedding_docs)

[[   0    0    0    0 8689 8540 7571 9726]
 [   0    0    0    0 8689 8540 7571 3456]
 [   0    0    0    0 8689 6634 7571 4490]
 [   0    0    0    0 4232 2022 5760 5615]
 [   0    0    0    0 4232 6697 5760 6982]
 [   0    0    0 5474 8689 9121 7571 9069]
 [   0    0    0    0 6471 5422   99 5760]]


In [20]:
## feature represntation
dim=10

In [21]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam', 'mse')

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
model.predict(embedding_docs)

1/1 [==============================] - 0s 170ms/step


array([[[-0.03692285, -0.01039775,  0.0209975 , -0.00801451,
         -0.00950295,  0.00886788,  0.0459989 , -0.00972061,
         -0.02808826,  0.03103502],
        [-0.03692285, -0.01039775,  0.0209975 , -0.00801451,
         -0.00950295,  0.00886788,  0.0459989 , -0.00972061,
         -0.02808826,  0.03103502],
        [-0.03692285, -0.01039775,  0.0209975 , -0.00801451,
         -0.00950295,  0.00886788,  0.0459989 , -0.00972061,
         -0.02808826,  0.03103502],
        [-0.03692285, -0.01039775,  0.0209975 , -0.00801451,
         -0.00950295,  0.00886788,  0.0459989 , -0.00972061,
         -0.02808826,  0.03103502],
        [-0.00995798,  0.02548406,  0.02619391, -0.02924532,
         -0.00028689, -0.00564939,  0.00437863,  0.02750191,
         -0.00644885,  0.00629687],
        [-0.00165689, -0.04764826, -0.00809296,  0.03776196,
          0.04806006,  0.0039691 ,  0.03270701, -0.00656779,
          0.01341016,  0.03367608],
        [ 0.02771456, -0.03803487, -0.01696103,  0.0

In [24]:
embedding_docs[0]

array([   0,    0,    0,    0, 8689, 8540, 7571, 9726])

In [29]:
model.predict(embedding_docs[0])

1/1 [==============================] - 0s 27ms/step


array([[-0.03692285, -0.01039775,  0.0209975 , -0.00801451, -0.00950295,
         0.00886788,  0.0459989 , -0.00972061, -0.02808826,  0.03103502],
       [-0.03692285, -0.01039775,  0.0209975 , -0.00801451, -0.00950295,
         0.00886788,  0.0459989 , -0.00972061, -0.02808826,  0.03103502],
       [-0.03692285, -0.01039775,  0.0209975 , -0.00801451, -0.00950295,
         0.00886788,  0.0459989 , -0.00972061, -0.02808826,  0.03103502],
       [-0.03692285, -0.01039775,  0.0209975 , -0.00801451, -0.00950295,
         0.00886788,  0.0459989 , -0.00972061, -0.02808826,  0.03103502],
       [-0.00995798,  0.02548406,  0.02619391, -0.02924532, -0.00028689,
        -0.00564939,  0.00437863,  0.02750191, -0.00644885,  0.00629687],
       [-0.00165689, -0.04764826, -0.00809296,  0.03776196,  0.04806006,
         0.0039691 ,  0.03270701, -0.00656779,  0.01341016,  0.03367608],
       [ 0.02771456, -0.03803487, -0.01696103,  0.04081526,  0.01179244,
        -0.03038732, -0.02121997, -0.01360927